# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

shared:
  image: vespaengine/vespa-pipeline:latest
  secrets:
    - DOCKER_HUB_DEPLOY_KEY

  environment:
    USER_SHELL_BIN: bash

  annotations:
    screwdriver.cd/cpu: HIGH
    screwdriver.cd/ram: HIGH
    screwdriver.cd/disk: HIGH
    screwdriver.cd/timeout: 30
    screwdriver.cd/dockerEnabled: true
    screwdriver.cd/dockerCpu: TURBO
    screwdriver.cd/dockerRam: TURBO

    inspect: &inspect
      inspect: |
        set -x
        env | grep -v TOKEN
        cat /proc/cpuinfo
        cat /proc/meminfo
        df -h
        uname -a

    install-deps: &install-deps
      install-deps: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum install -y docker-ce docker-ce-cli containerd.io
        docker system info

    build: &build
      build: |
        cd $CONTAINER_DIR
        docker build --tag $CONTAINER_IMAGE:$CONTAINER_VERSION .

    publish: &publish
      publish: |
        if [[ -z $SD_PULL_REQUEST ]]; then
          set +x
          docker login --username aressem --password "$DOCKER_HUB_DEPLOY_KEY"
          set -x

          docker push $CONTAINER_IMAGE:$CONTAINER_VERSION
        fi

    teardown-inspect: &teardown-inspect
      teardown-inspect: |
        docker image ls
        df -h

jobs:
  publish-build-centos-stream8:
    image: quay.io/centos/centos:stream8
    sourcePaths: ["screwdriver.yaml", "build/centos-stream8/"]
    requires: [~pr, ~commit]
    environment:
      CONTAINER_DIR: 'build/centos-stream8'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-build-centos-stream8'
      CONTAINER_VERSION: 'latest'
    steps:
      - *inspect
#      - *build
#      - *publish
      - build-multi-arch: |
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli skopeo

          # Fix auth
          set +x
          BASE64_AUTH=$(echo -n "aressem:$DOCKER_HUB_DEPLOY_KEY" | base64)
          echo "{\"auths\": {\"docker.io\": {\"auth\": \"$BASE64_AUTH\"}}}" > ~/.docker/config.json
          set -x
          mkdir -p ~/.docker

          cd $CONTAINER_DIR
          ls -al /certs/client
          docker info
          docker version
          docker buildx version
          docker buildx install
          unset DOCKER_HOST
          docker context create vespa-context --docker "host=tcp://localhost:2376,ca=/certs/client/ca.pem,cert=/certs/client/cert.pem,key=/certs/client/key.pem"
          docker context use vespa-context
          docker buildx create --name vespa-builder --driver docker-container --use
          docker buildx inspect --bootstrap

          docker context list
          docker buildx ls

          docker buildx build --progress plain --push --platform linux/amd64,linux/arm64 --tag $CONTAINER_IMAGE:$CONTAINER_VERSION .

          #set +x
          #skopeo login -u aressem -p "$DOCKER_HUB_DEPLOY_KEY" docker.io
          #set -x
          #skopeo copy --multi-arch all docker://local/image:latest docker://$CONTAINER_IMAGE:$CONTAINER_VERSION

      - teardown-clean: |
          rm -rf $HOME/.docker
