# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

shared:
  image: vespaengine/vespa-pipeline:latest
  secrets:
    - DOCKER_HUB_DEPLOY_KEY

  environment:
    USER_SHELL_BIN: bash

  annotations:
    screwdriver.cd/cpu: HIGH
    screwdriver.cd/ram: HIGH
    screwdriver.cd/disk: HIGH
    screwdriver.cd/timeout: 30
    screwdriver.cd/dockerEnabled: true
    screwdriver.cd/dockerCpu: TURBO
    screwdriver.cd/dockerRam: TURBO

    inspect: &inspect
      inspect: |
        set -x
        env | grep -v TOKEN
        cat /proc/cpuinfo
        cat /proc/meminfo
        df -h
        uname -a

    install-deps: &install-deps
      install-deps: |
        yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
        yum install -y docker-ce docker-ce-cli containerd.io
        docker system info

    build: &build
      build: |
        cd $CONTAINER_DIR
        docker build --tag $CONTAINER_IMAGE:$CONTAINER_VERSION .

    publish: &publish
      publish: |
        if [[ -z $SD_PULL_REQUEST ]]; then
          set +x
          docker login --username aressem --password "$DOCKER_HUB_DEPLOY_KEY"
          set -x

          docker push $CONTAINER_IMAGE:$CONTAINER_VERSION
        fi

    teardown-inspect: &teardown-inspect
      teardown-inspect: |
        docker image ls
        df -h
        rm -rf $HOME/.docker

jobs:
  publish-build-centos7:
    sourcePaths: ["screwdriver.yaml", "build/centos7/"]
    requires: [~commit]
    environment:
      CONTAINER_DIR: 'build/centos7'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-build-centos7'
      CONTAINER_VERSION: 'latest'
    steps:
      - *inspect
      - *install-deps
      - *build
      - *publish
      - *teardown-inspect

  publish-dev-centos7:
    sourcePaths: ["screwdriver.yaml", "dev/centos7/"]
    requires: [~commit, ~publish-build-centos7]
    environment:
      CONTAINER_DIR: 'dev/centos7'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-dev-centos7'
      CONTAINER_VERSION: 'latest'
    steps:
      - *inspect
      - *install-deps
      - *build
      - *publish
      - *teardown-inspect

  publish-build-centos-stream8:
    image: quay.io/centos/centos:stream8
    sourcePaths: ["screwdriver.yaml", "build/centos-stream8/"]
    requires: [~pr,~commit]
    environment:
      CONTAINER_DIR: 'build/centos-stream8'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-build-centos-stream8'
      CONTAINER_VERSION: 'latest'
    steps:
      - *inspect
      - install-deps: &bcsc-install-deps |
          dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
          dnf install -y docker-ce-cli
      - build-multi-arch: &bcsc-build-multi-arch |
          if [[ -z $SD_PULL_REQUEST ]]; then
            set +x
            docker login -u aressem -p $DOCKER_HUB_DEPLOY_KEY
            set -x
            DOCKER_BUILDX_PUSH="--push"
          fi

          cd $CONTAINER_DIR
          docker info
          docker version
          docker buildx version
          docker buildx install

          unset DOCKER_HOST
          docker context create vespa-context --docker "host=tcp://localhost:2376,ca=/certs/client/ca.pem,cert=/certs/client/cert.pem,key=/certs/client/key.pem"
          docker context use vespa-context

          docker buildx create --name vespa-builder --driver docker-container --use
          docker buildx inspect --bootstrap

          docker buildx build --progress plain $DOCKER_BUILDX_PUSH --platform linux/arm64 --tag $CONTAINER_IMAGE:$CONTAINER_VERSION .
      - *teardown-inspect

  publish-dev-centos-stream8:
    image: quay.io/centos/centos:stream8
    sourcePaths: ["screwdriver.yaml", "dev/centos-stream8/"]
    requires: [~commit, ~publish-build-centos-stream8]
    environment:
      CONTAINER_DIR: 'dev/centos-stream8'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-dev-centos-stream8'
      CONTAINER_VERSION: 'latest'
    steps:
      - *inspect
      - install-deps:     *bcsc-install-deps
      - build-multi-arch: *bcsc-build-multi-arch
      - *teardown-inspect
